name: Build

on: [push, workflow_dispatch]

jobs:
    test-workflow:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - run: echo "Hello build workflow"
