name: Build

on: [push, workflow_dispatch]

jobs:
    cmake:
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: [ubuntu-latest, windows-latest]

        steps:
            - uses: actions/checkout@v2

            - name: Build project
              run: |
                mkdir build
                cd build
                cmake --version
                cmake ..
                cmake --build .

            - name: Run unit tests
              run: |
                cd build
                cmake --build .
                ./UnitTest
