name: Build

on: [push, workflow_dispatch]

jobs:
    cmake:
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: [ubuntu-latest, windows-latest]
                include:
                  - os: windows-latest
                    exe-dir: Debug/

        steps:
            - uses: actions/checkout@v2

            - name: Build project
              run: |
                mkdir build
                cd build
                cmake --version
                cmake -DCMAKE_RUNTIME_OUTPUT_DIRECTORY_DEBUG=. ..
                cmake --build .

            - name: Run unit tests
              run: |
                cd build
                cmake --build .
                ctest -VV -C Debug
                #./${{ matrix.exe-dir }}UnitTest
